## Configure couchdb 'subchart'
clouseau:
  image:
    pullPolicy: IfNotPresent
    repository: cloudlesshq/clouseau
    tag: latest
couchdb:
  #adminUsername: jan
  #adminPassword: password
  #cookieAuthSecret: monster
  couchdbConfig:
    chttpd:
      bind_address: any
    httpd:
      bind_address: any
    log:
      level: info
      writer: stdout
  clusterSize: 3
  createAdminSecret: false
  enabled: true
  image:
    pullPolicy: IfNotPresent
    repository: cloudlesshq/couchdb
    # For local testing:
    # pullPolicy: Never
    # repository: couchdb-test
    tag: latest
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/rewrite-target: /
      nginx.ingress.kubernetes.io/enable-cors: "true"
    hosts:
      - couchdb.local
