## Configure couchdb 'subchart'
couchdb:
  adminUsername: jan
  adminPassword: password
  couchdbConfig:
    chttpd:
      bind_address: any
    httpd:
      bind_address: any
    log:
      level: info
      writer: stdout
  clusterSize: 3
  enabled: true
  image:
    pullPolicy: Never
    repository: couchdb-test
    tag: latest
