sudo: required

services:
  - docker

script:
  - make docker-lint

deploy:
  provider: script
  script: bash ./.travis/publish.sh
  on:
    branch: master

env:
  global:
  - secure: ILvEsrNytvqasmjpv4fwrFDKuXbK36raP15d4L0+6XoXci4VuCr0jsLjUu6Oo7F14iKnrPvZFIOlk5qdYAtARr7CaGG1RehLSACXwNQjOnvku2G5OLdHElRlEDRjpGTnTjqTjXprmh+JIWhrt2HNH/aInvtqYq4xGYXdLRkeSGQR0+hRztVZttw7Jgx2iLaNb3vwPjaQuaNqOd9i8k2LWfXxu2zwAB7eVXOfSUCPt+J7hWJnqBkwfCAQtO22pT3tsKk6OPq3d9V/3vvLAQRmsdlKe9F08/oVKqYSEEGrBL5Y6G6vyYl9tQp1u81vJCbIO0AOT6hx+m0VGsJegHX0wBjMFi+42I5TEBIUrOcU15VdLw1PkIAAZQKxgPeYUQIhtMCh8IF8pOHiyTOf0AyBRxs1jGv7xYWolOTclWsGKGh3hivsTsWBk+4PgiDynCYxjfGiC1Xr11w5QdDN+TFeOS6KuzcZUpFfQ3ZminBFeRXb2IHQodQ5B91PSHi61aXTGRSKWrNZz1OOV3Vx3MiVwEsZeRMLgKrFpBh8Uk466r1ZYZwtFmPQzHK9ML3cNDSy7eVmGWLqHaTFI3oZ9vFfH3mocUNbm5+V9k5wkk808v23NyadUN3570ZaSJzLSxphJSa3v4HPIdWHCXOtbipsL+38U8wDoKmaWD8Q9C7YGBQ=
  - secure: Vg6rpdU4EliPzdpL1Vc8mHHe/QCh0ZfUTctbEFKmZIhMtMVNCenUf2jGQBt2yVn5ZfCKg9LsAuGvkSZrcvzhMtD0kQOSRR5/aMoPCwIc+T8LVcv6zZjMVCUT5u2TH9kI5zxIMlwwJzWuhGphnJzh2wjcPQqYaujZ7I/vCJF2XpbRU07XqV6bDkjbVYEN6BtxvAPaSSpIp5xrBE149cbBygZP58LAdMVJcMnyxfbzrhOER7t/zOJixviDdw6XaOG0SCZCkTIv3kXSa+qi1vNl5BsFvbMuR9a+5fPnnBL193l0kT5xe7WyKyf8JVT45/Kae2lLSqUreo/TNQvo2KtWvqE63Vg98YH4xjc1uOi+oZJ9hAb/qBFYQBiSAaSn/q49zny8biUq3U/4mCPzrrTl2HWx77b0DLPn8DSLst6dtSPw7J3ez4tiLMnIIz1G/AWgorgzW7UsERm5DBcGmK7Kg83MqsjqMZx0WXGsfSV3jw+nWvSreAAa3inTfGIrKN5a0XIFhq8slk0i9uEEqeC9j2cJDVuU35wsgBMoRi+N9wgz6cGPEoRNgl1WNLmq4GF/wxHRQCkZ6qYM6Yslzy/90rVfkdUZ6SPCB+BAq9IABuyqcbxjoIyJLWjO6zaE27cC97ACdHxbR9HvnRZWTbm67bt7afL7m2ykTeIBwMucAA8=
