apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: foobar
  namespace: default
spec:
  encryptedData:
    foobar: AgCiYj+KJ7b0w76kbyTcXRpfdYlRXEUwg9TzNHEWWrP/LgfLa1fkmgQ2vapDwrMWxCJL3TmFtJfkyLpSRrE7UF45lfB0/b9SX1tDEBkwxe9w7AcRtq6JKpcLXyVjK/TZ2EFcjuCucw6ERXLtg3ocjbTOvTrWD4OGSLoqTwZQNFjmWgv1u+o5xZQ4AXP8iQ60+zZimTRDFP4k9xV6/ndkcGJqzvp2EYkvSlVduE6Ru50ExNKF9nqvfaFI0xes5gF6gd6Uji2oByVskx/e4OO3V/Vc3fN9Yc16/VxaG3SJJo4I0l+BhmqXIbP10EcfthFYTRq9RY77N/AfmPM/xAFIlaVeVa1dA4EKnwJ886bnVdRiNLKjnZIy7AL7nvL/WsvZDCFnnjm6FuBkKOmNNPl43e7V+ch07qktppgY3bId2taXXpHv32SmcPh0QE6uy1gopWJsZi7F4YUs5FgdaHwnqSIp8qBLgwjp7kp7rC1H9ADmH2QeUMl/FlKc7Ed4ZIBkkZ56bb7ZJ9YBCRkCus4nHYY3n3NZk4Lw77HBgbWW/s5lIXDBB5MVGscyUja+3/mLOvzCcpf5gVZJix+R6h7kJgn1tWCxUF0YWMhWCVmrmsLezSkVxaVd1Hn8FmXj+92ql8yhKRJkFV3xvtK9jp+GRnPr1aZ02/6EjLb/Vy4Foruj5HnstRrctTutNq2sH1s3T/cjPvWr849ScN8xar17i+Y55KJ1ySFBq57Eljhg5nawkP8M/UMA

